<?php 
    $data = [
        ["image" => "product1A.jpg", "image2" => "product1B.jpg", "description" => "Aliquip dolore amet reprehenderit aliquip nisi dolore. Non ipsum ipsum eiusmod cupidatat sunt non deserunt tempor. Duis id sit non ullamco aliquip anim proident excepteur aliquip. Laboris Lorem officia ut proident veniam culpa ullamco veniam quis consequat magna. Aute in nulla aute quis tempor.", "name" => "Brown Shirt", "price" => 550 ],
        ["image" => "product2A.jpg", "image2" => "product2B.jpg", "description" => "Aliquip dolore amet reprehenderit aliquip nisi dolore. Non ipsum ipsum eiusmod cupidatat sunt non deserunt tempor. Duis id sit non ullamco aliquip anim proident excepteur aliquip. Laboris Lorem officia ut proident veniam culpa ullamco veniam quis consequat magna. Aute in nulla aute quis tempor.", "name" => "Gray Shirt", "price" => 550],
        ["image" => "product3A.jpg", "image2" => "product3B.jpg", "description" => "Aliquip dolore amet reprehenderit aliquip nisi dolore. Non ipsum ipsum eiusmod cupidatat sunt non deserunt tempor. Duis id sit non ullamco aliquip anim proident excepteur aliquip. Laboris Lorem officia ut proident veniam culpa ullamco veniam quis consequat magna. Aute in nulla aute quis tempor.", "name" => "White Blazer", "price" => 750],
        ["image" => "product4A.jpg", "image2" => "product4B.jpg", "description" => "Aliquip dolore amet reprehenderit aliquip nisi dolore. Non ipsum ipsum eiusmod cupidatat sunt non deserunt tempor. Duis id sit non ullamco aliquip anim proident excepteur aliquip. Laboris Lorem officia ut proident veniam culpa ullamco veniam quis consequat magna. Aute in nulla aute quis tempor.", "name" => "Dark Blue Polo Shirt", "price" => 600],
        ["image" => "product5A.jpg", "image2" => "product5B.jpg", "description" => "Aliquip dolore amet reprehenderit aliquip nisi dolore. Non ipsum ipsum eiusmod cupidatat sunt non deserunt tempor. Duis id sit non ullamco aliquip anim proident excepteur aliquip. Laboris Lorem officia ut proident veniam culpa ullamco veniam quis consequat magna. Aute in nulla aute quis tempor.", "name" => "Dark Blue Long Sleeve", "price" => 800],
        ["image" => "product6A.jpg", "image2" => "product6B.jpg", "description" => "Aliquip dolore amet reprehenderit aliquip nisi dolore. Non ipsum ipsum eiusmod cupidatat sunt non deserunt tempor. Duis id sit non ullamco aliquip anim proident excepteur aliquip. Laboris Lorem officia ut proident veniam culpa ullamco veniam quis consequat magna. Aute in nulla aute quis tempor.", "name" => "White Long Sleeve", "price" => 800],
        ["image" => "product7A.jpg", "image2" => "product7B.jpg", "description" => "Aliquip dolore amet reprehenderit aliquip nisi dolore. Non ipsum ipsum eiusmod cupidatat sunt non deserunt tempor. Duis id sit non ullamco aliquip anim proident excepteur aliquip. Laboris Lorem officia ut proident veniam culpa ullamco veniam quis consequat magna. Aute in nulla aute quis tempor.", "name" => "Dark Blue Blazer", "price" => 750],
        ["image" => "product8A.jpg", "image2" => "product8B.jpg", "description" => "Aliquip dolore amet reprehenderit aliquip nisi dolore. Non ipsum ipsum eiusmod cupidatat sunt non deserunt tempor. Duis id sit non ullamco aliquip anim proident excepteur aliquip. Laboris Lorem officia ut proident veniam culpa ullamco veniam quis consequat magna. Aute in nulla aute quis tempor.", "name" => "Floral Polo", "price" => 650]
    ];
?>
